### ISSUE TITLE
Support sending direct messages

### ISSUE THREAD

**Issue by akerl** [dghubble/go-twitter#117] opened 2018-08-22 16:17 UTC
It looks like current support is limited to reading existing DMs, is that correct?

I was hoping for access to https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/new-event

**Comment by dghubble** [comment] 2018-08-22 18:00
Of the new endpoints, only list has been added so far.

**Comment by dghubble** [comment] 2018-11-18 08:07
Duplicate of #122

**Closed by dghubble** 2018-11-18 08:07 UTC
